/*
 * Author: Lucas
 * Version: 0.1
 * Datum 01.12.2017
 * */
#ifndef ENUMERATIONS
#define ENUMERATIONS

enum BUTTONSTATE{ ENABLED, DISABLED };
enum MATCHFIELDSTATE{ ACTIVE, INACTIVE, TARGET, WAITING };
enum DEPTH{ FLAT, NORMAL, DEEP };

#endif // ENUMERATIONS

