#ifndef ENUMERATIONS
#define ENUMERATIONS

enum BUTTONSTATE{ ENABLED, DISABLED };
enum MATCHFIELDSTATE{ ACTIVE, INACTIVE, TARGET, WAITING };
enum DEPTH{ FLAT, NORMAL, DEEP };

#endif // ENUMERATIONS

